// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/pgvector/pgvector-go"
)

type File struct {
	ID        int32
	Filename  string
	Content   string
	Embedding pgvector.Vector
}
