name: RAG Logic CI/CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'rag-logic/**'
      - '.github/workflows/rag-logic-workflow.yaml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'rag-logic/**'
      - '.github/workflows/rag-logic-workflow.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/rag-logic

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-linting-${{ hashFiles('rag-logic/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-linting-

      - name: Install linting dependencies
        working-directory: rag-logic
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy bandit

      - name: Run Black (Code Formatting)
        working-directory: rag-logic
        run: black --check --diff app/

      - name: Run isort (Import Sorting)
        working-directory: rag-logic
        run: isort --check-only --diff app/

      - name: Run Flake8 (Style Guide)
        working-directory: rag-logic
        run: flake8 app/

      - name: Run MyPy (Type Checking)
        working-directory: rag-logic
        run: mypy app/ --ignore-missing-imports

      - name: Run Bandit (Security Linting)
        working-directory: rag-logic
        run: bandit -r app/ -f json -o bandit-report.json || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-security-report
          path: rag-logic/bandit-report.json

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('rag-logic/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: rag-logic
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio httpx

      - name: Run Unit Tests
        working-directory: rag-logic
        run: pytest tests/ -v --tb=short -m "not slow and not integration" --cov=app --cov-report=xml --cov-report=html

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            rag-logic/coverage.xml
            rag-logic/htmlcov/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: rag-logic/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install security scanning dependencies
        working-directory: rag-logic
        run: |
          python -m pip install --upgrade pip
          pip install safety>=2.0.0

      - name: Run Safety (Dependency Security Check)
        working-directory: rag-logic
        run: safety check --json --output safety-report.json || true

      - name: Upload Safety Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: safety-security-report
          path: rag-logic/safety-report.json

  docker-build-and-test:
    name: Docker Build and Test
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./rag-logic
          load: true
          tags: |
            rag-logic:${{ github.sha }}
            rag-logic:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Test Docker container
        run: |
          # Start container in background
          docker run -d -p 8000:8000 --name test-container rag-logic:latest
          
          # Wait for container to be ready
          sleep 30
          
          # Test the API endpoint
          curl -f http://localhost:8000/docs || exit 1
          
          # Stop container
          docker stop test-container
          docker rm test-container

  docker-push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: [docker-build-and-test, security-scan]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/rag-logic
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./rag-logic
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  docker-security-scan:
    name: Docker Security Scan with Trivy
    runs-on: ubuntu-latest
    needs: docker-build-and-test
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t rag-logic:${{ github.sha }} ./rag-logic --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}"
          docker tag rag-logic:${{ github.sha }} rag-logic:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'rag-logic:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner (JSON format)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'rag-logic:latest'
          format: 'json'
          output: 'trivy-results.json'

      - name: Upload Trivy JSON Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-security-report
          path: trivy-results.json

  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [lint, test, security-scan, docker-build-and-test, docker-security-scan, docker-push]
    if: always()
    steps:
      - name: Notify on Success
        if: ${{ needs.lint.result == 'success' && needs.test.result == 'success' && needs.security-scan.result == 'success' && needs.docker-build-and-test.result == 'success' }}
        run: |
          echo "✅ All critical checks passed for RAG Logic!"
          echo "- Linting: ${{ needs.lint.result }}"
          echo "- Tests: ${{ needs.test.result }}"
          echo "- Security Scan: ${{ needs.security-scan.result }}"
          echo "- Docker Build & Test: ${{ needs.docker-build-and-test.result }}"
          echo "- Docker Security Scan: ${{ needs.docker-security-scan.result }} (non-blocking)"
          echo "- Docker Push: ${{ needs.docker-push.result }} (conditional)"

      - name: Notify on Failure
        if: ${{ needs.lint.result == 'failure' || needs.test.result == 'failure' || needs.security-scan.result == 'failure' || needs.docker-build-and-test.result == 'failure' }}
        run: |
          echo "❌ Some critical checks failed for RAG Logic!"
          echo "- Linting: ${{ needs.lint.result }}"
          echo "- Tests: ${{ needs.test.result }}"
          echo "- Security Scan: ${{ needs.security-scan.result }}"
          echo "- Docker Build & Test: ${{ needs.docker-build-and-test.result }}"
          echo "- Docker Security Scan: ${{ needs.docker-security-scan.result }} (non-blocking)"
          echo "- Docker Push: ${{ needs.docker-push.result }} (conditional)"
          exit 1
