name: RAG Embedding Service CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'rag-embedding-service/**'
      - '.github/workflows/rag-embedding-service-workflow.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'rag-embedding-service/**'
      - '.github/workflows/rag-embedding-service-workflow.yml'

defaults:
  run:
    working-directory: ./rag-embedding-service

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Black (Code Formatting)
        run: black --check --diff app/ tests/

      - name: Run isort (Import Sorting)
        run: isort --check-only --diff app/ tests/

      - name: Run Flake8 (Style Guide)
        run: flake8 app/ tests/

      - name: Run MyPy (Type Checking)
        run: mypy app/ --ignore-missing-imports

      - name: Run Bandit (Security Linting)
        run: bandit -r app/ -f json -o bandit-report.json || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-security-report
          path: rag-embedding-service/bandit-report.json

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Unit Tests
        run: pytest tests/ -v --tb=short -m "not slow and not integration" --cov=app --cov-report=xml --cov-report=html

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-reports
          path: |
            rag-embedding-service/coverage.xml
            rag-embedding-service/htmlcov/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./rag-embedding-service/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Safety (Dependency Security Check)
        run: safety check --json --output safety-report.json || true

      - name: Upload Safety Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: safety-security-report
          path: rag-embedding-service/safety-report.json

  docker-build-and-test:
    name: Docker Build and Test
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t rag-embedding-service:${{ github.sha }} .
          docker tag rag-embedding-service:${{ github.sha }} rag-embedding-service:latest

      - name: Test Docker container
        run: |
          # Start container in background
          docker run -d -p 8001:8001 --name test-container rag-embedding-service:latest
          
          # Wait for container to be ready
          sleep 30
          
          # Test the API endpoint
          curl -f -X POST "http://localhost:8001/embed" \
               -H "Content-Type: application/json" \
               -d '{"text": "Hello world"}' || exit 1
          
          # Stop container
          docker stop test-container
          docker rm test-container

  docker-security-scan:
    name: Docker Security Scan with Trivy
    runs-on: ubuntu-latest
    needs: docker-build-and-test
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t rag-embedding-service:${{ github.sha }} .
          docker tag rag-embedding-service:${{ github.sha }} rag-embedding-service:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rag-embedding-service:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner (JSON format)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rag-embedding-service:latest'
          format: 'json'
          output: 'trivy-results.json'

      - name: Upload Trivy JSON Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy-security-report
          path: trivy-results.json

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, security-scan, docker-security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/rag-embedding-service
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./rag-embedding-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [lint, test, security-scan, docker-build-and-test, docker-security-scan]
    if: always()
    steps:
      - name: Notify on Success
        if: ${{ needs.lint.result == 'success' && needs.test.result == 'success' && needs.security-scan.result == 'success' && needs.docker-build-and-test.result == 'success' }}
        run: |
          echo "✅ All checks passed for RAG Embedding Service!"
          echo "- Linting: ${{ needs.lint.result }}"
          echo "- Tests: ${{ needs.test.result }}"
          echo "- Security Scan: ${{ needs.security-scan.result }}"
          echo "- Docker Build & Test: ${{ needs.docker-build-and-test.result }}"
          echo "- Docker Security Scan: ${{ needs.docker-security-scan.result }}"

      - name: Notify on Failure
        if: ${{ needs.lint.result == 'failure' || needs.test.result == 'failure' || needs.security-scan.result == 'failure' || needs.docker-build-and-test.result == 'failure' }}
        run: |
          echo "❌ Some checks failed for RAG Embedding Service!"
          echo "- Linting: ${{ needs.lint.result }}"
          echo "- Tests: ${{ needs.test.result }}"
          echo "- Security Scan: ${{ needs.security-scan.result }}"
          echo "- Docker Build & Test: ${{ needs.docker-build-and-test.result }}"
          echo "- Docker Security Scan: ${{ needs.docker-security-scan.result }}"
          exit 1 